name: Security audit

on:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  safety:
    name: Safety
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: {{ cookiecutter.python_version }}
    - run: pip install poetry nox safety
    - run: poetry install
    - run: nox -s safety
